name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install black ruff
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run Linters
        run: |
          black --check .
          ruff check .
          shellcheck -x src/installers/**/*.sh

  test-rhel:
    name: Test RHEL Installer on ${{ matrix.distro }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        distro: [rockylinux:9, centos:7, almalinux:8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x src/installers/rhel/qradar_rhel_installer.sh

      - name: Run RHEL installer in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app -e CI=true ${{ matrix.distro }} bash -c "
            yum install -y rsyslog audit python3 || true &&
            /app/src/installers/rhel/qradar_rhel_installer.sh 127.0.0.1 514 --dry-run &&
            grep 'target=\"127.0.0.1\"' /etc/rsyslog.d/99-qradar.conf &&
            test -f /app/qradar_rhel_setup.log"

      - name: Relocate installer log
        if: always()
        run: |
          sudo mv qradar_rhel_setup.log $RUNNER_TEMP/ || true
          sudo chown $USER:$USER $RUNNER_TEMP/qradar_rhel_setup.log || true

      - name: Upload installer log
        uses: actions/upload-artifact@v4
        with:
          name: rhel-installer-log-${{ matrix.distro }}
          path: ${{ runner.temp }}/qradar_rhel_setup.log

  test-debian:
    name: Test Debian Installer on ${{ matrix.distro }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        distro: [debian:11, debian:10, kali/kali-rolling]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x src/installers/debian/qradar_debian_installer.sh

      - name: Run Debian installer in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app -e CI=true ${{ matrix.distro }} bash -c "
            apt-get update && apt-get install -y rsyslog auditd python3 || true &&
            /app/src/installers/debian/qradar_debian_installer.sh 127.0.0.1 514 --dry-run &&
            grep 'target=\"127.0.0.1\"' /etc/rsyslog.d/99-qradar.conf &&
            test -f /app/qradar_debian_setup.log"

      - name: Relocate installer log
        if: always()
        run: |
          sudo mv qradar_debian_setup.log $RUNNER_TEMP/ || true
          sudo chown $USER:$USER $RUNNER_TEMP/qradar_debian_setup.log || true

      - name: Upload installer log
        uses: actions/upload-artifact@v4
        with:
          name: debian-installer-log-${{ matrix.distro }}
          path: ${{ runner.temp }}/qradar_debian_setup.log

  test-ubuntu:
    name: Test Ubuntu Installer on ${{ matrix.distro }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        distro: [ubuntu:22.04, ubuntu:20.04, ubuntu:18.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x src/installers/ubuntu/qradar_ubuntu_installer.sh

      - name: Run Ubuntu installer in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app -e CI=true ${{ matrix.distro }} bash -c "
            apt-get update && apt-get install -y rsyslog auditd python3 || true &&
            /app/src/installers/ubuntu/qradar_ubuntu_installer.sh 127.0.0.1 514 --dry-run &&
            grep 'target=\"127.0.0.1\"' /etc/rsyslog.d/99-qradar.conf &&
            test -f /app/qradar_ubuntu_setup.log"

      - name: Relocate installer log
        if: always()
        run: |
          sudo mv qradar_ubuntu_setup.log $RUNNER_TEMP/ || true
          sudo chown $USER:$USER $RUNNER_TEMP/qradar_ubuntu_setup.log || true

      - name: Upload installer log
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-installer-log-${{ matrix.distro }}
          path: ${{ runner.temp }}/qradar_ubuntu_setup.log
