# Trivial change to force re-read of the workflow file.
name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install black ruff
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run Linters
        run: |
          black --check .
          ruff check .
          shellcheck -x src/installers/**/*.sh

  test-universal-installer:
    name: Test Universal Installer on ${{ matrix.distro }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        distro: [rockylinux:9, centos:7, almalinux:8, debian:11, debian:10, kali/kali-rolling, ubuntu:22.04, ubuntu:20.04, ubuntu:18.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x src/installers/universal/qradar_universal_installer.sh

      - name: Run Universal installer in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app -w /app -e CI=true ${{ matrix.distro }} bash -c "
            if [[ \"${{ matrix.distro }}\" == \"rockylinux:9\" || \"${{ matrix.distro }}\" == \"centos:7\" || \"${{ matrix.distro }}\" == \"almalinux:8\" ]]; then
              yum install -y rsyslog audit python3 || true;
            else
              apt-get update && apt-get install -y rsyslog auditd python3 || true;
            fi &&
            /app/src/installers/universal/qradar_universal_installer.sh 127.0.0.1 514 --dry-run &&
            grep 'target=\"127.0.0.1\"' /etc/rsyslog.d/99-qradar.conf &&
            test -f /app/qradar_universal_setup.log"

      - name: Relocate installer log
        if: always()
        run: |
          sudo mv qradar_universal_setup.log $RUNNER_TEMP/ || true
          sudo chown $USER:$USER $RUNNER_TEMP/qradar_universal_setup.log || true

      - name: Upload installer log
        uses: actions/upload-artifact@v4
        with:
          name: universal-installer-log-${{ matrix.distro }}
          path: ${{ runner.temp }}/qradar_universal_setup.log
